import argparse
from pathlib import Path
import pandas as pd

from llm_culture.analysis.utils import get_stories, get_plotting_infos, initialize_nltk, preprocess_stories, get_similarity_matrix
from llm_culture.analysis.utils import compute_between_gen_similarities, get_polarities_subjectivities
from llm_culture.analysis.plots import run_configured_plots




def _compute_analysis_data(folder, font_sizes):
    all_seeds_stories = get_stories(folder)

    print(f"Number of stories: {len(all_seeds_stories)}\n")
    n_seeds = len(all_seeds_stories)
    n_gen, n_agents, x_ticks_space = get_plotting_infos(all_seeds_stories[0])

    all_seeds_flat_stories, all_seeds_keywords, all_seeds_stem_words = preprocess_stories(all_seeds_stories)
    all_seeds_similarity_matrix = get_similarity_matrix(all_seeds_flat_stories)
    all_seeds_between_gen_similarity_matrix = compute_between_gen_similarities(all_seeds_similarity_matrix, n_gen, n_agents)
    all_seeds_polarities, all_seeds_subjectivities = get_polarities_subjectivities(all_seeds_stories)
    # all_seeds_creativities = get_creativity_indexes(all_seeds_stories, folder)
    # embedding_points = plot_embedding(folder, False, sizes=font_sizes, save=False)

    return {
        'n_seeds': n_seeds,
        'n_gen': n_gen,
        'n_agents': n_agents,
        'x_ticks_space': x_ticks_space,
        'all_seeds_stories': all_seeds_stories,
        'all_seeds_flat_stories': all_seeds_flat_stories,
        'all_seeds_keywords': all_seeds_keywords,
        'all_seeds_stem_words': all_seeds_stem_words,
        'all_seeds_similarity_matrix': all_seeds_similarity_matrix,
        'all_seeds_between_gen_similarity_matrix': all_seeds_between_gen_similarity_matrix,
        # 'all_seeds_polarities': all_seeds_polarities,
        # 'all_seeds_subjectivities': all_seeds_subjectivities,
        # 'all_seeds_creativities': all_seeds_creativities,
        # 'embedding_points': embedding_points,
    }


def _load_or_compute_analysis_data(folder, font_sizes, cache_file_name='analysis_cache_df.pkl', force_recompute_cache=False):
    cache_path = Path(folder) / cache_file_name

    if cache_path.exists() and not force_recompute_cache:
        print(f"Loading cached analysis DataFrame from {cache_path}")
        cache_df = pd.read_pickle(cache_path)
        if len(cache_df) == 0:
            raise ValueError(f"Cache file is empty: {cache_path}")
        return cache_df.iloc[0].to_dict()

    print("No usable cache found, computing analysis data...")
    analysis_data = _compute_analysis_data(folder, font_sizes)
    cache_df = pd.DataFrame([analysis_data])
    cache_df.to_pickle(cache_path)
    print(f"Saved analysis cache DataFrame to {cache_path}")
    return analysis_data


def main_analysis(
    folder,
    font_sizes={'ticks': 12, 'labels': 14, 'title': 16},
    plot=False,
    cache_file_name='analysis_cache_df.pkl',
    force_recompute_cache=False,
    plot_configs=None,
):
    """Main function to run the analysis on the stories generated by the simulation

    :param folder: folder containing the stories
    :param font_sizes: font_size for the plots, defaults to {'ticks': 12, 'labels': 14, 'title': 16}
    :param plot: wether to plot or not, defaults to False
    """
    analysis_data = _load_or_compute_analysis_data(
        folder,
        font_sizes,
        cache_file_name=cache_file_name,
        force_recompute_cache=force_recompute_cache,
    )

    run_configured_plots(analysis_data, folder, plot=plot, sizes=font_sizes, plot_names=plot_configs)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--dir", type=str, default="FC_10_10_combine_mixedPop_5seeds")
    parser.add_argument("--folder", type=str, default=None, help="Full or repo-relative folder to analyze (overrides --dir)")
    parser.add_argument("--plot", action="store_true")
    parser.add_argument("--cache_file", type=str, default="analysis_cache_df.pkl")
    parser.add_argument("--force_recompute_cache", action="store_true")
    parser.add_argument("--ticks_font_size", type=int, default=12)
    parser.add_argument("--labels_font_size", type=int, default=14)
    parser.add_argument("--title_font_size", type=int, default=16)
    args = parser.parse_args()

    initialize_nltk()

    if args.folder is not None:
        analyzed_dir = Path(args.folder)
        if not analyzed_dir.exists():
            analyzed_dir = Path.cwd() / args.folder
    else:
        analyzed_dir = Path("results") / args.dir

    if not analyzed_dir.exists():
        raise FileNotFoundError(f"Analysis folder not found: {analyzed_dir}")

    analyzed_dir = str(analyzed_dir)
    
    font_sizes = {
        'ticks': args.ticks_font_size,
        'labels': args.labels_font_size,
        'title': args.title_font_size
    }
    
    print(f"\nLaunching analysis on the {analyzed_dir} results")
    print(f"plot = {args.plot}")
    main_analysis(
        analyzed_dir,
        font_sizes,
        args.plot,
        cache_file_name=args.cache_file,
        force_recompute_cache=args.force_recompute_cache,
    )
